name: shopping
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  icons_plus:
  sqflite:
  path:
  path_provider:
  http:
  dio:
  share_plus:
  awesome_dialog:
  shared_preferences:
  google_fonts:

  # Firebase dependencies
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  firebase_messaging: ^14.7.19
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  introduction_screen:

  intl: any
  internet_connection_checker_plus: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/slider.png
    - assets/images/slider2.png
    - assets/images/slider3.png
    - assets/images/4.png
    - assets/fonts/

  fonts:
    - family: Amiri-Regular
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
